# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

condition_fleet_effort <- function(fl, dim, sim_yrs, mean_yrs) {
    .Call('_FLBEIA_condition_fleet_effort', PACKAGE = 'FLBEIA', fl, dim, sim_yrs, mean_yrs)
}

condition_flcatches <- function(fl, SLwt, SDwt, B, st, mean_yrs_q, mean_yrs_wts, mean_yrs_sel, sim_yrs, LO, UseCWt4Discards) {
    .Call('_FLBEIA_condition_flcatches', PACKAGE = 'FLBEIA', fl, SLwt, SDwt, B, st, mean_yrs_q, mean_yrs_wts, mean_yrs_sel, sim_yrs, LO, UseCWt4Discards)
}

